name: Docker Image CI

env:
  DOCKER: docker.io
  IMAGENAME: samba

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 8 1 * *'

jobs:
  vulerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - vulerability-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER }}/liwanggui/${{ env.IMAGENAME }}:latest
            ${{ env.DOCKER }}/liwanggui/${{ env.IMAGENAME }}:${{ steps.date.outputs.date }}

